### ISSUE TITLE
Example no longer works on 0.19.1

### ISSUE THREAD

**Issue by adamocarolli** [rerun-io/web-viewer-react-example#1]
This example no longer works on 0.19.1 works on 0.17.0 if I move back webviewer version. See deployment: https://rerun-io.github.io/web-viewer-react-example/

(<Select ..> styling must also be changed to be made viewable)

Console error:
```
index-5ba4b9da.js:40 ReferenceError: cachedFloat32Memory0 is not defined
    at AsyncFunction.le [as deinit] (re_viewer-87986463.js:2:81960)
    at we.free (index-5ba4b9da.js:40:58804)
    at js.stop (index-5ba4b9da.js:40:60791)
    at cv.componentDidUpdate (index-5ba4b9da.js:62:536)
    at As (index-5ba4b9da.js:40:31663)
    at yd (index-5ba4b9da.js:40:31351)
    at Tm (index-5ba4b9da.js:40:30910)
    at zm (index-5ba4b9da.js:40:40717)
    at Gt (index-5ba4b9da.js:40:40083)
    at Vs (index-5ba4b9da.js:40:36722)

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'closure14713_externref_shim')
    at te (re_viewer-87986463.js:2:2049)
    at c (re_viewer-87986463.js:2:265)
```

Using Chrome: Version 131.0.6778.86 (Official Build) (arm64)

**Comment by adamocarolli** [comment]
<img width="556" alt="Screenshot 2024-11-27 at 11 58 27 AM" src="https://github.com/user-attachments/assets/c0529a36-3547-4092-86ff-49040bb70e25">
